### ISSUE TITLE
example usage of sauce plugin options in a wct.conf.js file?

### ISSUE THREAD

**Issue by ckortekaas** [Polymer/wct-sauce#2]
Hi,

Thanks for making WCT - it's great!

Just wondering how an example of how to setup wct.conf.js in the root dir of an app should look.

This doesn't seem to work with wct --sauce:
```
module.exports = {
  plugins: {sauce: { browsers: {
        browserName: "internet explorer",
        platform:    "Windows 8.1",
        version:     "11"
      }}}
};
```
It just gives:
```
'-plugins.sauce.browsers' expects a value
```

**Comment by ckortekaas** [comment]
I figured it out. I was two issues:

1 - I needed to use 'wct --plugin sauce' on the command line
2 - the array/object structure should have been more like this:

```
module.exports = {
  verbose: true,
  browsers: [],
  plugins: {
    sauce: {
      browsers: [
      {
        browserName: "iphone",
        platform: "OS X 10.9",
        version: "8.1",
        deviceName: "iPhone Simulator",
        "device-orientation": "portrait"
      }
  ]}
}
};
```

**Comment by summisudhi** [comment]
Getting Could not find WCT plugin named "sauce" any suggestion
